### ISSUE TITLE
シナリオ分岐

### ISSUE THREAD

**Issue by Kohei-Nagano** [Kohei-Nagano/2017_05-Novel#6]
プレイヤーのパラメータによって、分岐を判断

**Comment by ghost** [comment]
ゲーム側で終了時に関数を呼べばシナリオ切り替えできる
ゲーム側でノベルを取得しておく
ゲームのインスタンス生成時にノベルを渡せばOK（novel.js）ではすでに渡してるので
main側であらためて変数つくって受け取ってください
